name: CI

on: [ push, pull_request, workflow_dispatch ]

jobs:
  build:
    runs-on: macos-13

    steps:
      - uses: actions/checkout@v3

      - name: Run a multi-line script
        run: |
          brew install virtualbox
          brew install qemu
          sudo xcode-select -s /Applications/Xcode_15.0.1.app
          xcodebuild test -scheme ilia -destination "platform=iOS Simulator,name=iPad (10th generation)"
          
